const categories = ["General", "Junior", "Premier", "Senior", "Sub junior"];
const teams = ["Mustansiriyah", "Tahriyya", "Qarawiyyah"];
const fieldNames = {
  itemId: "Item",
  firstPrize: "First Prize",
  firstTeam: "First Team",
  secPrize: "Second Prize",
  secTeam: "Second Team",
  thirdPrize: "Third Prize",
  thirdTeam: "Third Team",
  categoryId: "Category",
};

const itemsByCategory = {
  General: [
    "Alfiya Mushara",
    "Book Test",
    "Burdha Cat A",
    "Calligraphy",
    "Campus Song",
    "Cooking",
    "Documentary Presentation",
    "E Poster",
    "Group Song Cat A",
    "Group Song Cat B",
    "Hadees Musabaqa",
    "Kaviyarang",
    "Mathrubhasha",
    "Nasheeda Cat B",
    "Nilapadu",
    "Photography",
    "Podcast",
    "PowerPoint Presentation",
    "Press Meet",
    "Project",
    "Qawali",
    "Reel Making",
    "Spiritual Speech",
    "Spot Magazine",
    "Sufi Geetham",
    "Vlogging",
  ],
  Junior: [
    "Caption Writing",
    "Elocution English",
    "Elocution Malayalam",
    "Essay Writing English",
    "Essay Writing Malayalam",
    "Madh Song",
    "Pencil Drawing",
    "Pusthaka Charcha",
    "Qirath",
    "Quran Quiz",
    "Story Writing English",
    "Story Writing Malayalam",
    "Tech Presentation",
    "Verification English",
    "Verification Malayalam",
  ],
  Premier: [
    "Azan Call",
    "Bakki Njan Paranjolam",
    "Cube Solving",
    "Fiqh Demonstration",
    "Ganitha Kali",
    "Handwriting",
    "Hifz",
    "Madh Song",
    "Memory Test",
    "Pencil Drawing",
    "Puzzle",
    "Qirath",
    "Quiz",
    "Story Telling",
    "Story Writing English",
    "Story Writing Malayalam",
    "Verification English",
    "Verification Malayalam",
    "Water Coloring",
  ],
  Senior: [
    "Arabic Speech",
    "Caption Writing",
    "Content Writing",
    "Essay Writing English",
    "Essay Writing Malayalam",
    "Extempore Malayalam",
    "Global Thadrees",
    "Hifz Test",
    "Hiku Malayalam",
    "Ideal Speech",
    "Madh Song",
    "News Writing",
    "Poem Appreciation",
    "Poem Presentation English",
    "Public Talk",
    "Quran Test",
    "Story Writing Arabic",
    "Story Writing English",
    "Story Writing Malayalam",
    "Thafseer Talk",
    "Translation Eng-Arb",
    "Verification English",
  ],
  "Sub junior": [
    "Arabic Reading",
    "Azan Call",
    "Cube Solving",
    "Elocution Malayalam",
    "Essay Writing English",
    "Essay Writing Malayalam",
    "Handwriting Arabic",
    "Hifz",
    "Instant Dawa",
    "Listening Test",
    "Madh Song",
    "Mappila Patt",
    "Mashke Muqabala",
    "News Presentation",
    "Pencil Drawing",
    "Quiz",
    "Spell Bee",
    "Story Writing English",
    "Story Writing Malayalam",
    "Sudoku",
    "Verification English",
    "Verification Malayalam",
    "Water Coloring",
    "Word Game Arabic",
  ],
};

const steps = [
  "Add all teams, categories, and items before starting the program.",
  "You can start adding results only after starting the program.",
  "Once the program is started, you cannot edit or delete teams, categories, or items.",
  "If you need to make changes, you must stop the program first.",
  "Stopping the program will delete all added results.",
  "There's also a reset button to clear all data and start fresh.",
];


const slides = [
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_spi_zjcq6h.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/357480395_572652891493163_603989940549611415_n_nyk12s.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/358020129_2541173729369497_4997410294927867411_n_vudwn3.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_spi_zjcq6h.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_1_jwnfab.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_2_gywuvn.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982138/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_3_rh0wn1.jpg",
];
export { categories, teams, itemsByCategory, slides ,steps,fieldNames};
